### PR TITLE
Missing inline decls

### PR DESCRIPTION
**Pull request by bchoi**
- fully-specialized templated functions
- implemented functions in header files

### CODE REVIEW

**Comment by pcolby** [comment]
Thanks @bchoi! :+1: 

I had to go a read up on fully-specialized template functions! :smile:

**Comment by bchoi** [comment]
@pcolby Not a problem. Thank you for this awesome library!

**Comment by pcolby** [comment]
Hey @bchoi,

Just FYI, the email address you used to make these changes (byn dot choi at sap dot com) is not recognised by Github as belonging to you.  This isn't a problem, but does mean that you get less credit from Github recognising those changes as yours.

Its not necessary, but I'd recommend you go into your [Github Email settings](https://github.com/settings/emails), and add that address as an additional address for your account. Then, for example, Github should list you as one of the contributors at https://github.com/pcolby/pcp-pmda-cpp/graphs/contributors :smile:

Cheers.

**Comment by bchoi** [comment]
Paul-

Thanks for letting me know! I've added my work address there now so
hopefully that'll resolve github's confusion :)

Thanks again for the great library, I love how clean and intuitive the
interface is.

Byn

**Comment by pcolby** [comment]
:+1: :smile:

**Pull request merged**
